refactor : 상품 조회, 상세조회 코드 재구성
sky1231234/shoppingMall pull request #1
Opened 2024-03-05 08:05 UTC by sky1231234

DTO 내 이너클래스를 분리하고, service에서 이루어지는 builder를 리턴 클래스 of 메소드로 변경

2024-03-07 07:08 UTC, ryan-nomad commented on src/main/java/com/project/shop/item/controller/ItemController.java
> +    private final ItemServiceImpl itemServiceImpl;
ItemService 를 인터페이스로 추상화하여 Impl에서 구현하는 시도가 좋았네요 :) 
추상화를 한 이유는 다형성을 이용하기 위함이겠죠!? 하지만 코드에는 다형성을 이용하지 않았어요.
아래 내용 고민해보고 같이 이야기해봐요.
- 왜 다형성을 적용했는지?
- 다형성을 적용한 후 장점과 단점이 무엇인지?

```suggestion
    private final ItemService itemServiceImpl;
```

2024-03-07 07:08 UTC, ryan-nomad commented on src/main/java/com/project/shop/item/domain/Item.java
> +    public void updateItemInfo(Category category, String itemName, int price, String explain){
리뷰 반영 👍

2024-03-07 07:27 UTC, ryan-nomad requested changes
양선님 첫 PR 올리시느라 고생하셨어요.
리뷰 내용 한번 쭉 읽어보시고 의견 달아주세요.
 + 해결 완료시 resolve check! 해주세요.
 
아시는 내용이겠지만 Pull Request는 push만 하시면 계속 open 된 상태에서 변경내용이 반영되면서 리뷰어와 계속 핑퐁할 수 있어요.(승인되거나 거절될때까지!) 

그럼 오늘도 화이팅입니다 !

2024-03-07 07:27 UTC, ryan-nomad commented on src/main/java/com/project/shop/item/dto/request/ImgRequest.java
> +    public ItemImg toEntity(Item item){
Request에서 완전한 Entity를 만드는 것을 보장 할 수 있을까요?

2024-03-07 07:27 UTC, ryan-nomad commented on src/main/java/com/project/shop/item/dto/response/OptionColor.java
> +public class OptionColor {
유의미한 도메인에 대해 클래스로 정의 내린 부분 좋아요 🤞🏻

2024-03-07 07:27 UTC, ryan-nomad commented on src/main/java/com/project/shop/item/repository/ItemImgRepository.java
> +    List<ItemImg> findByItemAndItemImgType(Item item, ItemImgType imgType);
아이템 이미지만 조회하는 케이스가 많을까요?
아이템 이미지는 아이템에 항상 딸려서 조회되는 케이스가 많다면 양방향 연관관계 설정 후 Item에 포함되게 하는 방향은 어떻게 생각하세요?

2024-03-07 07:27 UTC, ryan-nomad commented on src/main/java/com/project/shop/item/service/ItemServiceImpl.java
> +        OptionDetails optionDetails = getOptionByItem(item);
Item을 인자로 받는 메소드가 4개 호출되고 있네요. SRP(하나의책임 원칙)을 생각해서 유의미한 메소드로 추출하는건 어떨까요?

2024-03-07 07:27 UTC, ryan-nomad commented on src/test/java/com/project/shop/item/builder/ItemBuilder.java
test에만 사용되는 파일이라면 좀 더 명확한 이름을 가져도 좋을 것 같아요.

test fixture에 관련된 자료를 한번 찾아보고 반영해볼까요?

2024-03-07 16:28 UTC, sky1231234 commented on src/main/java/com/project/shop/item/repository/ItemImgRepository.java
> +    List<ItemImg> findByItemAndItemImgType(Item item, ItemImgType imgType);
이미지만 조회하는 경우는 없습니다.
하지만 이미지 없이 상품의 간단한 상품 정보만 조회하는 경우(상품 전체 조회)에도 상품 별로 등록된 이미지가 모두 조회 되면 성능 저하되지 않나요?

2024-03-07 16:59 UTC, sky1231234 commented on src/main/java/com/project/shop/item/service/ItemServiceImpl.java
> +        OptionDetails optionDetails = getOptionByItem(item);
item 인자로 받는 메소드들과 리턴 메소드 분리했습니다

2024-03-08 10:03 UTC, ryan-nomad commented on src/main/java/com/project/shop/item/repository/ItemImgRepository.java
> +    List<ItemImg> findByItemAndItemImgType(Item item, ItemImgType imgType);
이미지만 조회되는 경우가 없다면 요구사항에 맞는 응답을 한번에 처리할 수 있도록
native query / JPQL / QueryDSL 을 적용하여 DB I/O와 비지니스 로직 영역에서의 연산을 동시에 줄이는 방법은 어떨까요?

* itemImg를 조회하는 것보다 최종 결과물인 Item을 조회하고 그 안에 조건에 맞는 ItemImg가 딸려오는 방식

일반적으로 애플리케이션에서 연산되는 비용보다 DB I/O 비용이 커요. 요구사항에 맞는 결과물을 한번의 쿼리로 처리하는 것이 좋을지, 로직 연산과정에서 계속 호출하는 것이 좋을지 고민해보는 건 어떨까요?

*as-is : items가 순휘하면서 findByItemAndItemImgType 을 호출하는 구조

2024-03-11 05:03 UTC, ryan-nomad approved these changes

2024-03-11 05:33 UTC, sky1231234 commented on src/main/java/com/project/shop/item/controller/ItemController.java
> +    private final ItemServiceImpl itemServiceImpl;
다형성을 이용하면 기능의 변화나 리팩토링의 이유로 메소드 수정이 이루어져도
메소드 호출부는 수정 사항 없이 구현부만 수정하면 된다. 
하지만 현재 서비스는 한 개의 클래스로 이루어져 있고, 서비스가 늘어날 가능성이 적기 때문에 itemService에서 구현하고 호출하게 한다.

2024-03-11 05:43 UTC, sky1231234 commented on src/main/java/com/project/shop/item/repository/ItemImgRepository.java
> +    List<ItemImg> findByItemAndItemImgType(Item item, ItemImgType imgType);
to-be : 양방향 설정 후 item을 조회하면 item에 포함되는 itemImg도 한번에 조회

2024-03-11 07:51 UTC, merged