Develop
sky1231234/shoppingMall pull request #2
Opened 2024-03-15 17:07 UTC by sky1231234

repositoryTest를 통해 orderSheet entity, repository 생성하였습니다.

기존 order Entity와 새로 만드는 주문서가  비슷한 역할을 포함한 것 같은데, 사실 주문서의 역할이 헷갈려서 말씀하셨던 필수 기능을 구현하는데 포인트를 두고 생각하고 있습니다.

2024-03-21 06:34 UTC, ryan-nomad commented
DB조회 등 외부 의존성이 발생하는 경우는 통합테스트의 영역으로 넘어가요.
1. 등록된 상품인지
2. 등록된 옵션인지
이 값들이 DB로 관리되고있다면 service 영역에서 검증할 수 있을 것 같아요. 상품서비스나, 옵션서비스의 책임과 협력하는 방식이 되겠죠?
3,4번에 대해서도 책임과 관련하여 코멘트 드렸으니 한 번 고민해보시길 바래요.

추가로 사이드 이펙트가 발생하는 영역은 mock으로, 발생하지 않는 영역은 stub으로 대체해요. 
db repository는 stub으로 해결할 수 있을 것 같아요.

2024-03-21 06:36 UTC, ryan-nomad requested changes

2024-03-21 06:36 UTC, ryan-nomad commented on src/test/java/com/project/shop/ordersheet/domain/OrderSheetTest.java
> +        assertEquals(상품리스트.get(1).getOrderQuantity(), 3);
매직넘버 3이 보이네요.
```suggestion
        assertEquals(상품리스트.get(1).getOrderQuantity(), 두번째_주문상품_수량);
```

상품은 두개를 등록했는데 검증은 하나만 한 것 같아요.
첫번째_주문상품에 대한 수량이 틀렸다면 이 테스트의 신뢰도가 떨어질것같아요.

2024-03-21 06:36 UTC, ryan-nomad commented on src/test/java/com/project/shop/ordersheet/domain/OrderSheetTest.java
> +        assertThat(exception.getMessage()).isEqualTo("주문 상품은 최소 1개 이상이여야한다.");
메세지의 내용까지 비교하는 것을 의도했다면, 메세지가 상수로 정의되는 것은 어떨까요?

2024-03-21 06:36 UTC, ryan-nomad commented on src/main/java/com/project/shop/ordersheet/domain/OrderSheet.java
> +  LocalDateTime now = LocalDateTime.now();
이 코드의 목적을 설명해주세요.

2024-03-21 06:36 UTC, ryan-nomad commented on src/main/java/com/project/shop/ordersheet/domain/OrderSheetItem.java
> +    public void validateItemPrice(int itemPrice){
ItemPrice가 Item안에 있게 된다면, 이 책임은 Item안에서 해결 될 것 같아요.
Item과 Item의 Price가 독립적으로 존재해야할 이유가 있는 걸까요?

2024-03-21 06:36 UTC, ryan-nomad commented on src/main/java/com/project/shop/ordersheet/domain/OrderSheetItem.java
> +        if (orderQuantity < 1){
매직넘버.. 매직넘버..

2024-03-21 06:36 UTC, ryan-nomad commented on src/test/java/com/project/shop/ordersheet/domain/OrderSheetItemTest.java
> +        int 주문수량 = 0;
비정상 데이터임을 추론할수있는 이름을 가지면 더 명확해질 것 같아요.

2024-03-21 13:13 UTC, sky1231234 commented on src/main/java/com/project/shop/ordersheet/domain/OrderSheet.java
> +  LocalDateTime now = LocalDateTime.now();
LocalDateTime now = LocalDateTime.now(); 코드는 리팩토링 중 삭제하지 못했습니다.

2024-03-21 14:31 UTC, sky1231234 commented
service에서 등록된 상품/옵션인지 검사하면
OrderSheetItem이 생성되면서 파라미터 유효성 검사할 때 이미 등록 여부가 확인 된 파라미터니 따로 검사를 하지않아도 되는거네요? 그렇게 되면 단위 테스트로 검사할 예외에도 포함되지 않고요.

2024-03-26 00:41 UTC, ryan-nomad approved these changes
- 첫 번째 질문에 대한 의견
orderSheetItemTest 보다는 도메인룰이 아닌 비지니스룰이라 판단되어 OrderSheetServiceTest에서 이루어지면 될 것 같아요. repository 의존성 등이 필요해 보이네요.

**또 item에 itemPrice가 있기 때문에 독립적일 이유가 없네요!
그러면 자연스레 OrderSheetItem에서 itemPrice가 빠지면서 OrderSheetItemTest에서 상품가격 예외 테스트하는 코드는 필요없어지게 되겠죠?! (이것도 맞을까요?)**
->  같은 생각입니다.^^

2024-03-26 08:28 UTC, merged